meta_product_name: "Vitta"
meta_title: "Vitta - Encontre os melhores médicos próximos a você!"
meta_description: "Nós mostramos a você os melhores médicos de sua região de acordo com a especialidade pesquisada."
meta_image: "cover.png"
